### ISSUE TITLE
As a business stakeholder, I want to be able to interact with the charts and key model outputs so that I can explore the data and gain a better understanding of the insights.

### ISSUE THREAD

**Issue by saurabhsainani** [ivm25/marketing_mix_modelling#1]
### Estimation of effort

TBD

### Acceptance criteria

- The charts and key model outputs are presented in an interactive format.
- Business stakeholders can easily navigate and explore the charts and model outputs.
- The charts and model outputs are visually appealing and effectively communicate the insights.
- The user interface has been tested and validated with representative business stakeholders to ensure it meets their needs and expectations.
- Feedback from business stakeholders has been incorporated to improve the usability and effectiveness of the charts and model outputs.

**Comment by ivm25** [comment]
- The aim of the issue seems right, with the ability to interact with charts and key model  @saurabhsainani, maybe change "non technical" to business stakeholders?

- Estimation of effort:
- It will involve quite a bit of re engineering and learning of some new concepts,
   1.  Specifically callbacks in dash (to allow interactivity). My estimation is 2-3 weeks of work.
   2. To enable sharing of the dashboard in dash involves hosting the app on a server. I estimate a further 2-3 weeks for this process.
- Acceptance Criteria:

- The charts and key model outputs are presented in an interactive format.

- **[ Achievable, the first step will involve making a simple chart that works with interactive dropdowns]** 

- Non-technical stakeholders can easily navigate and explore the charts and model outputs.

- **[That can happen once the plotly dashboard is hosted on a server.  Can provide pngs/jpgs of the dashboard to preview in the coming few weeks. ] .**

- The charts and model outputs are visually appealing and effectively communicate the insights.

- **[ Yes, agree on this.]** 

- The user interface is accessible and supported on various devices and screen sizes.


- **[ I am unable to comment on this point just yet, as I will have to test this and also learn on this works for plotly. In short, I dont have knowledge yet to make this happen.]** 

-The user interface has been tested and validated with representative non-technical stakeholders to ensure it meets their needs and expectations.

- **[Yes, agree on this. For this to work, I need to host the work and aligns with my previous point on hosting on a server. ]** 

- Feedback from non-technical stakeholders has been incorporated to improve the usability and effectiveness of the charts and model outputs.

- **[ Yes, no issues with this going forward. It will also become clear whether plotly-dash is the right choice of tooling for this to work. We might have to pivot to a different tooling in case plotly -dash becomes too cumbersome to make it functional.]**

**Comment by saurabhsainani** [comment]
> * The aim of the issue seems right, with the ability to interact with charts and key model  @saurabhsainani, maybe change "non technical" to business stakeholders?

Done

> * Estimation of effort:
> * It will involve quite a bit of re engineering and learning of some new concepts,
>   
>   1. Specifically callbacks in dash (to allow interactivity). My estimation is 2-3 weeks of work.
>   2. To enable sharing of the dashboard in dash involves hosting the app on a server. I estimate a further 2-3 weeks for this process.

We can do a relative estimating exercise using a concept of story points that might be helpful to estimate the effort required, not just for this feature but all user stories going forward. We can discuss this when we connect next?

> * Acceptance Criteria:
> * The charts and key model outputs are presented in an interactive format.
> * **[ Achievable, the first step will involve making a simple chart that works with interactive dropdowns]**
> * Non-technical stakeholders can easily navigate and explore the charts and model outputs.
> * **[That can happen once the plotly dashboard is hosted on a server.  Can provide pngs/jpgs of the dashboard to preview in the coming few weeks. ] .**
> * The charts and model outputs are visually appealing and effectively communicate the insights.
> * **[ Yes, agree on this.]**
> * The user interface is accessible and supported on various devices and screen sizes.
> * **[ I am unable to comment on this point just yet, as I will have to test this and also learn on this works for plotly. In short, I dont have knowledge yet to make this happen.]**

> We can remove this from the acceptance criteria for now? As this is not an immediate priority?

> -The user interface has been tested and validated with representative non-technical stakeholders to ensure it meets their needs and expectations.
> 
> * **[Yes, agree on this. For this to work, I need to host the work and aligns with my previous point on hosting on a server. ]**
> * Feedback from non-technical stakeholders has been incorporated to improve the usability and effectiveness of the charts and model outputs.
> * **[ Yes, no issues with this going forward. It will also become clear whether plotly-dash is the right choice of tooling for this to work. We might have to pivot to a different tooling in case plotly -dash becomes too cumbersome to make it functional.]**

**Comment by ivm25** [comment]
- We can do a relative estimating exercise using a concept of story points that might be helpful to estimate the effort required, not just for this feature but all user stories going forward. We can discuss this when we connect next?

- **Okay, sounds good to me.** 


- We can remove this from the acceptance criteria for now? As this is not an immediate priority?

**Yes, I feel we could do away with this for now.**

**Comment by ivm25** [comment]
User story :The charts and key model outputs are presented in an interactive format:

- I have managed to create a first draft of three key charts, that show a basic model fit, coefficients of the variables and a more detailed model output. 
- I am still working on optimising the formatting and look of the charts.

Attaching here a web capture:
![landing page_marketing_mix_modelling](https://github.com/ivm25/marketing_mix_modelling/assets/44321100/bf4d48c4-a504-4ca7-9e76-054aaf8c631e)

**Comment by ivm25** [comment]
- Non-technical stakeholders can easily navigate and explore the charts and model outputs.

**1. I have been able to host the output charts on a server now: https://marketingmixmodelling-example-v7cxq7rr2a-ts.a.run.app/
2. This link should open up for anyone now and the charts can be interacted with now.
3. See if this opens for you properly. 
4. On the first chart (scatter chart), you should be able to double click on any of the legend names and the chart should change.**

**Comment by ivm25** [comment]
- The updated link for the hosted service is : https://marketingmixmodelling-dashexample.onrender.com/
